<?php

$title = 'ACQUISTA';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<div>
    <?php /** @var \Application\Entity\Concert $concert */ ?>
    <p><label>gruppo: </label><?= $concert->getArtist() ?></p>
    <p><label>luogo: </label><?= $concert->getLocation() ?></p>
    <p><label>data: </label><?= date_format($concert->getDate(), 'd-m-Y') ?></p>
    <p><label>prezzo: </label><?= $concert->getPrice() ?> €</p>
</div>

<?php if ($concert->getAvailability() > 0) : ?>
    <a class="btn btn-success" href="<?= $this->url('concert', ['action' => 'pay-concert', 'id' => $concert->getId()]) ?>">Paga ora</a>
<?php else : ?>
    <p>Biglietti esauriti</p>
<?php endif; ?>

