
<?php
// module/Concert/view/concert/concert/index.phtml:

$title = 'CONCERTI';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<table class="table">
    <tr>
        <th>Gruppo</th>
        <th>Luogo</th>
        <th>Prezzo</th>
        <th>Disponibilità</th>
        
    </tr>
    <?php foreach ($concerts as $concert) : ?>
        <tr>
            <td><?= $concert->getArtist() ?></td>
            <td><?= $concert->getLocation() ?></td>
            <td><?= $concert->getPrice() ?></td>
            <td><?= $concert->getAvailability() ?></td>
        </tr>
    <?php endforeach; ?>
</table>
