<?php
$title = 'Login ' . $userTypeName;
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?php
$email = $form->get('email');
$email->setAttribute('class', 'form-control');

$password = $form->get('password');
$password->setAttribute('class', 'form-control');

$submit = $form->get('login_submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('user', ['action' => 'login-' . $userTypeCode]));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['alert', 'alert-danger']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($password) ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>



<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div class="alert alert-danger">
                                
                            ')
        ->setMessageSeparatorString('</p><p>')
        ->setMessageCloseString('</div>');

echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
echo $this->formSubmit($submit);
echo $this->form()->closeTag();


