<?php
$title = 'Login ' . $userTypeName;
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?php
$email = $form->get('email');
$email->setAttribute('class', 'form-control');

$password = $form->get('password');
$password->setAttribute('class', 'form-control');

$submit = $form->get('login_submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('user', ['action' => 'login-' . $userTypeCode]));
$form->prepare();

echo $this->form()->openTag($form);
?>

<?php /* if ($userTypeCode == 'organizer') : ?>

  <div class="form-group">
  <?= $this->formLabel($company) ?>
  <?= $this->formElement($company) ?>
  <?= $this->formElementErrors()->render($company, ['class' => 'help-block']) ?>
  </div>

  <div class="form-group">
  <?= $this->formLabel($vat) ?>
  <?= $this->formElement($vat) ?>
  <?= $this->formElementErrors()->render($vat, ['class' => 'help-block']) ?>
  </div>

  <?php endif; */ ?>

<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['alert', 'alert-danger']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($password) ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>



<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div class="alert alert-danger">
                                <p>Credenziali non valide.</p>
                                
                            ')
        ->setMessageSeparatorString('</p><p>')
        ->setMessageCloseString('</div>');

echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));

echo $this->formSubmit($submit);
echo $this->form()->closeTag();


